### ISSUE TITLE
changes in OSX Sierra, High Sierra

### ISSUE THREAD

**Issue by phaag** [attilathedud/mem_scan#1] opened 2017-12-03 12:36 UTC
Hi 
I noticed, that a lot of processes are not longer attachable even if the binary is signed ( self signed CERT ) 
Are there any changes in the Mach Kernel regarding task_for_pid() ?

Thanks

**Comment by attilathedud** [comment] 2017-12-04 02:25
Thank you for the bug report. I haven't upgraded yet to latest version of OSX, so I can't verify this issue. 

Could you please give me an example of a program you attached to on El Capitan but doesn't work on Sierra?

**Comment by phaag** [comment] 2017-12-07 15:51
Unfortunately I have no El Capitan to compare - I just noticed that even user processes such as safari are not attachable. From the entire process list, at least halve are not attachable. 
To codesign the binary makes no difference.

**Comment by attilathedud** [comment] 2017-12-10 07:20
Are the processes you can't attach to only Apple signed binaries (e.g., Safari, Notepad, etc.) or do they included downloaded applications as well (such as Chrome)?

**Comment by phaag** [comment] 2017-12-12 09:48
Almost all extra installed software, incl. VMware Fusion, X11 (XQuartz) all X11 Apps, Thunderbird etc do work, however interestingly Google Chrome does not work either. All Apple preinstalled Apps and processed resulting thereof don't. I check trough the entire process list.

**Comment by attilathedud** [comment] 2017-12-13 09:38
Thanks for all the work you have done with this. Apple must have slightly tweaked the security code for attaching to processes. When I am able, I will download High Sierra and work on fixing the issue. For now, I will keep this issue open.

**Comment by phaag** [comment] 2017-12-15 09:44
Thx! If I can help, let me know ....

**Comment by phaag** [comment] 2017-12-19 14:43
Seems as also on latest el Capitan, they changed the security model:

host% ps
  PID TTY           TIME CMD
80225 ttys000    0:01.26 -csh
37982 ttys001    0:00.29 -csh
41498 ttys010    0:00.75 -csh
41582 ttys013    0:00.46 -csh
host% sudo ./mem_scan -p 80225 -r 56
task_for_pid failed: (os/kern) failure

**Comment by attilathedud** [comment] 2017-12-22 05:55
Haven't investigated the el Capitan issue, but since it might be caused by a different issues, I broke it out into a new issue #2

**Comment by attilathedud** [comment] 2017-12-24 09:45
So did some research tonight, and not a lot of good results.

As for a lot of the processes not being attachable, I found this interesting bug report from the Chromium devs [here.](https://bugs.chromium.org/p/chromium/issues/detail?id=523041) It seems applications have to sign their code a certain way to allow attaching to them via task_for_pid. As a result, if an application is signed and distributed through the App Store then task_for_pid will fail unless that application grants the 'restrict' flag. 

I was curious if this affected other memory scanners like Bit Slicer, and apparently it does. With System Integrity Protection enabled, task_for_pid will fail unless the above is done when the app is signed. All Apple applications and Google Chrome apparently use SIP. You can see the issues logged by Bit Slicer [here.](https://github.com/zorgiepoo/Bit-Slicer/issues/32)

So the options are to either disable SIP or create a copy of any desired application and sign it with a fake cert.

Since there is nothing else I can really do in this regard, I am closing this issue. Thanks for pointing it out though.

**Closed as completed by attilathedud** 2017-12-24 09:45 UTC

**Comment by phaag** [comment] 2017-12-24 11:40
Thanks anyway for your time investigating this issue! It is very much appreciated!
